modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL=""
[[mods]]
modId="magicksaddon"
version="${file.jarVersion}"
displayName="Kingdom Keys - Re:Mind"
displayURL=""
credits="Credits to the Kingdom Keys Dev team for helping make this possible."
authors="Xephiro"
description='''
A magic mod that adds on to what Kingdom Keys has with elements from other KH titles as well as various Final Fantasy titles.
'''
[[dependencies.magicksaddon]]
modId="kingdomkeys"
mandatory=true
versionRange="[1.20.1-2.3.10.3,)"
ordering="AFTER"
side="BOTH"
[[dependencies.magicksaddon]]
modId="epicfight"
mandatory=false
versionRange="[18.3,)"
ordering="AFTER"
side="BOTH"